#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createMutable(__DIR__);
$dotenv->safeLoad();

function env($string, $default = '')
{
    return $_ENV[$string] ?? $default;
}

function dd($item)
{
    echo "\n";
    print_r($item);
    echo "\n";
    die;
}

if (!empty($argv) && !empty($argv[1])) {
    $arg = $argv[1];

    $explosion = explode(':', $arg, 2);

    $commandNameParts = explode('-', $explosion[0]);
    $commandNameParts = array_map(function ($item) {
        return ucfirst($item);
    }, $commandNameParts);

    $command = implode('', $commandNameParts);


    $path = "App\Commands\\$command";
    $params = array_slice($argv, 2);

    new $path($explosion[0], ...$params);
}
